-- CreateEnum
CREATE TYPE "PermissionType" AS ENUM ('ADD_CAR', 'DELETE_CAR', 'EDIT_CAR', 'VIEW_ALL_CARS', 'VIEW_AVAILABLE_CARS', 'VIEW_ALL_BOOKING', 'ADD_BOOKING', 'DELETE_BOOKING', 'EDIT_BOOKING', 'MANGAGE_PAYMENT');
